### ISSUE TITLE
some other datasets

### ISSUE THREAD

**Issue by Extord1108** [maduc7/Histopathology-Datasets#3]
Hi, your collection is really helpful!  I have come across some datasets while reading [this paper](https://doi.org/10.1038/s41591-024-02857-3). Maybe you need them:

Other datasets from TCIA
https://www.cancerimagingarchive.net/browse-collections/

Datasets published by Tolkach Y. et al.
https://zenodo.org/records/7548828

BMIRDS Datasets
https://bmirds.github.io/

anti-panCK
https://zenodo.org/records/7412731

AGGC Datasets
https://aggc22.grand-challenge.org/Data/

**Comment by maduc7** [comment]
Hi @Extord1108 thanks for your message, would you be up to create a PR to add them in the table? Then you can also be a contributor to the repository :)

**Comment by Extord1108** [comment]
I have added seven new datasets in #4 , but TICA has too many datasets and it's too difficult for me to add all of them alone. Maybe we can work together to finish it. 😊

**Comment by maduc7** [comment]
Thanks a lot for your contribution. Yes I know TCIA has a lot of resources and it is difficult to keep track of those, but I think they are less focused on histopathology. Unfortunately I do not have time to look at those and add them, but feel free to add some of them whenever you have time. I am happy to see more people contributing to this repository.
