### ISSUE TITLE
Potential some error for organ

### ISSUE THREAD

**Issue by Younger330** [maduc7/Histopathology-Datasets#6]
Your work is greatly appreciated and is really helpful.However, while conducting experiments with these datasets, I have encountered a potential issue regarding the classification of organs.

I noticed that CPM-15 lists 2 classes of organs, whereas CPM-17 lists 4 classes of organs. However, , both the CPM-15 and CPM-17 datasets originate from brain tissue. This raises the question of whether there has been a confusion between the concepts of organs and tissues in the table.

Besides, Some cell detection datasets are missed, such as "Count-ception: Counting by fully convolutional redundant counting" .

**Comment by Younger330** [comment]
I have conducted many pathological datasets and can I contribute to this repository as a participant?

**Comment by maduc7** [comment]
Hello,

There can be some issues of course, and I am happy if people are corrected them. 
Please just create pull requests with the changes you want and I will review them or ask others to review them.

**Comment by Younger330** [comment]
Hello,

I have corrected some errors and added some datasets. Please review them at your convenience.

Thank you :)

**Comment by Younger330** [comment]
> Hello,
> 
> There can be some issues of course, and I am happy if people are corrected them. Please just create pull requests with the changes you want and I will review them or ask others to review them.

Hello,

I have corrected some errors and added some datasets. Please review them at your convenience.

Thank you :)
